locals {
  inventory = <<EOT
# Generated by Terraform
---
all:
  vars:
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  hosts:
    ${var.wg_hostname}:
      ansible_host: ${resource.digitalocean_droplet.wireguard_host.ipv4_address}
      ansible_port: 22
      ansible_user: root
      ansible_ssh_private_key_file: ${var.do_priv_key} 
      ansible_python_interpreter: /usr/bin/python3
EOT
}

resource "local_file" "ansible_inventory" {
  content              = local.inventory
  filename             = "../ansible/inventory.yaml"
  directory_permission = "0750"
  file_permission      = "0640"
}

output "ansible_inventory" {
  value = local.inventory
}
